config/routes.rb
Rails.application.routes.draw do
  
resources :users
resources :users do
    member do
    get :following, :followers
  end
end

resources :sessions, only: [:new, :create, :destroy]
resources :microposts, only: [:create, :destroy]
resources :relationships, only: [:create, :destroy]
get '/signup', to: 'users#new'
get '/signin', to: 'sessions#new'

  root to: 'static_pages#home'
get '/signup',to: 'users#new'

get '/help',   to: 'static_pages#help'
get '/about', to: 'static_pages#about'
get '/contact',to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="https://www.facebook.com/ranaumairy">Rails Tweet</a>
		by Umair Ejaz
	</small>
	<nav>
		<ul>
			<li><%= link_to "About",about_path %></li>
			<li><%= link_to "Contact",contact_path %></li>
			<li><a>News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
			<div class="navbar navbar-inner navbar-inverse ">
				<div class="container">
					<%= link_to "Tweet",root_path,id:"logo" %>
					<nav>
						<ul class="nav nav-tabs pull-right tabhover ">
							<li><%= link_to "Home", root_path %></li>
							<li><%= link_to "Help", help_path  %></li>
							<% if signed_in? %>
								<li><%= link_to "Users", users_path %></li>
								<li id="fat-menu" class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Account <b class="caret"></b>
									</a>
									<ul class="dropdown-menu home">
										<li><%= link_to "Profile", current_user %></li>
										<li><%= link_to "Settings", edit_user_path(current_user) %></li>
										<li class="divider"></li>
										<li>
											<%= link_to "Sign out", session_path(current_user) , method: :delete %>
										</li>
									</ul>
								</li>
								<% else %>
									<li><%= link_to "Sign In",signin_path%></li>
								<% end %>
						</ul>
					</nav>
				</div>
			</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application" , media: "all"  %>
  <%= javascript_include_tag 'http://code.jquery.com/jquery-2.1.4.min.js'%>

  <%= javascript_include_tag 'application'  %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		
	</div>
	</body>
</html>